version: '3'
services:
  web:
    build:
      context: .
    container_name: go-osa
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_USERNAME=test123@test.com
      - PGADMIN_DEFAULT_PASSWORD=test123