name: Deployment file to server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy file to server
          uses: burnett01/rsync-deployments@4.1
          with:
            switches: -avzr --delete --exclude=".git" --exclude=".github"
            path: /
            remote_path: ${{ secrets.DEPLOY_PATH }}
            remote_host: ${{ secrets.SSH_HOST }}
            remote_user: ${{ secrets.SSH_USERNAME }}
            remote_key: ${{ secrets.SSH_PRIVATE_KEY }}